var redditData = {
"kind": "Listing",
"data": {
"modhash": "",
"children": [
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;My brand new husband and I somehow got lucky enough to honeymoon at Seabrook Island. What is there to do here besides golf? Because neither of us have enough disposable income to learn how to golf.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "My brand new husband and I somehow got lucky enough to honeymoon at Seabrook Island. What is there to do here besides golf? Because neither of us have enough disposable income to learn how to golf.",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3ph8ec",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "AssChapstick",
"media": null,
"score": 6,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 13,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3ph8ec/seabrook_island_sc/",
"name": "t3_3ph8ec",
"created": 1445369066,
"url": "https://www.reddit.com/r/Charleston/comments/3ph8ec/seabrook_island_sc/",
"author_flair_text": null,
"quarantine": false,
"title": "Seabrook Island, SC",
"created_utc": 1445340266,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 6
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Got water in the intake, tried to start it... and I&amp;#39;m fearing for the worst. I just moved here, and I need to sort this out rather quickly. &lt;/p&gt;\n\n&lt;p&gt;I need to have it towed by AAA to the mechanic, so I&amp;#39;m hoping it&amp;#39;s not too far.&lt;/p&gt;\n\n&lt;p&gt;Thanks for any and all help!&lt;/p&gt;\n\n&lt;p&gt;edit title: my*&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Got water in the intake, tried to start it... and I'm fearing for the worst. I just moved here, and I need to sort this out rather quickly. \n\nI need to have it towed by AAA to the mechanic, so I'm hoping it's not too far.\n\nThanks for any and all help!\n\n\nedit title: my*",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3pdlwq",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "Roulbs",
"media": null,
"score": 6,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 12,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3pdlwq/need_a_mechanic_for_mpossibly_totaledlexus_gs400/",
"name": "t3_3pdlwq",
"created": 1445304666,
"url": "https://www.reddit.com/r/Charleston/comments/3pdlwq/need_a_mechanic_for_mpossibly_totaledlexus_gs400/",
"author_flair_text": null,
"quarantine": false,
"title": "Need a mechanic for m--possibly totaled--Lexus GS400, I live in downtown Charleston.",
"created_utc": 1445275866,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 6
}
},
{
"kind": "t3",
"data": {
"domain": "i.imgur.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3pde9e",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "Mr_Spade",
"media": null,
"score": 7,
"approved_by": null,
"over_18": false,
"hidden": false,
"preview": {
"images": [
{
"source": {
"url": "https://i.redditmedia.com/Ij-zI7kUnUzsJEBP6FXtM1VIYtsT_LJ1phgogrTnaJI.jpg?s=b8ab66a74421066fd27abefb5c832ada",
"width": 3120,
"height": 4160
},
"resolutions": [
{
"url": "https://i.redditmedia.com/Ij-zI7kUnUzsJEBP6FXtM1VIYtsT_LJ1phgogrTnaJI.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=11e19cce22bbbd2223ea0f41a36a1277",
"width": 108,
"height": 144
},
{
"url": "https://i.redditmedia.com/Ij-zI7kUnUzsJEBP6FXtM1VIYtsT_LJ1phgogrTnaJI.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=62a5634c36add1483f255aecc96b28ef",
"width": 216,
"height": 288
},
{
"url": "https://i.redditmedia.com/Ij-zI7kUnUzsJEBP6FXtM1VIYtsT_LJ1phgogrTnaJI.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=e2bd2cdda2cc36bbb1eda8634d72006a",
"width": 320,
"height": 426
},
{
"url": "https://i.redditmedia.com/Ij-zI7kUnUzsJEBP6FXtM1VIYtsT_LJ1phgogrTnaJI.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=4823ddabf3c95b1870d569e2ee735605",
"width": 640,
"height": 853
},
{
"url": "https://i.redditmedia.com/Ij-zI7kUnUzsJEBP6FXtM1VIYtsT_LJ1phgogrTnaJI.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=960&amp;s=cf1c750ba2f6a36ea7ccc4a2d439459e",
"width": 960,
"height": 1280
},
{
"url": "https://i.redditmedia.com/Ij-zI7kUnUzsJEBP6FXtM1VIYtsT_LJ1phgogrTnaJI.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=1080&amp;s=84360f301280bbb8b226352ada052884",
"width": 1080,
"height": 1440
}
],
"variants": {},
"id": "7ay4PRaS7WXP5EQ5k4fzzRm9ohwf6XXs-YBTdk4X44s"
}
]
},
"num_comments": 8,
"thumbnail": "http://b.thumbs.redditmedia.com/cfmoDwlCGDnxlU8uUzJmgOrTMgkd0cgAPFka3Rj56Hw.jpg",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"post_hint": "image",
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/3pde9e/so_have_any_of_you_all_done_this_food_challenge/",
"name": "t3_3pde9e",
"created": 1445301689,
"url": "http://i.imgur.com/1ZPG9F6.jpg",
"author_flair_text": null,
"quarantine": false,
"title": "So have any of you all done this food challenge yet?",
"created_utc": 1445272889,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 7
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I&amp;#39;m trying to get into the technical writing field. I have seen a lot of job openings in the area, and I heard the pay is decent. &lt;/p&gt;\n\n&lt;p&gt;I majored in communications and worked as a sports reporter in college and then full time as a writer and editor of a daily paper for almost 2 years. I wasn&amp;#39;t making any money so I quit that job, moved back to Charleston and got a data entry job. (So thrilling, really.)&lt;/p&gt;\n\n&lt;p&gt;I can write and proofread well, and love doing it. I&amp;#39;m also obsessed with learning and grasp things quickly without needing to be shown multiple times. So I think I would do well. However, I don&amp;#39;t have a technical background. I&amp;#39;m teaching myself some basic coding online, but I just started that last week.&lt;/p&gt;\n\n&lt;p&gt;I want to talk to someone who is in the field about how to get started, because all the postings want 5-10 years experience. Thanks! Sorry this isn&amp;#39;t exactly Charleston related.&lt;/p&gt;\n\n&lt;p&gt;Edit: Forgot to add that I currently write for a local blog and freelance for newspapers occasionally.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I'm trying to get into the technical writing field. I have seen a lot of job openings in the area, and I heard the pay is decent. \n\nI majored in communications and worked as a sports reporter in college and then full time as a writer and editor of a daily paper for almost 2 years. I wasn't making any money so I quit that job, moved back to Charleston and got a data entry job. (So thrilling, really.)\n\nI can write and proofread well, and love doing it. I'm also obsessed with learning and grasp things quickly without needing to be shown multiple times. So I think I would do well. However, I don't have a technical background. I'm teaching myself some basic coding online, but I just started that last week.\n\nI want to talk to someone who is in the field about how to get started, because all the postings want 5-10 years experience. Thanks! Sorry this isn't exactly Charleston related.\n\nEdit: Forgot to add that I currently write for a local blog and freelance for newspapers occasionally.",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3pcvga",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "niorec",
"media": null,
"score": 9,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 3,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": 1445273617,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3pcvga/any_technical_writers_around/",
"name": "t3_3pcvga",
"created": 1445293920,
"url": "https://www.reddit.com/r/Charleston/comments/3pcvga/any_technical_writers_around/",
"author_flair_text": null,
"quarantine": false,
"title": "Any technical writers around?",
"created_utc": 1445265120,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 9
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;How&amp;#39;s the hoa?  I&amp;#39;m really hesitant to buy a home under a hoa, but we have got to find something bigger.   Experiences?  Advice?  Thanks&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "How's the hoa?  I'm really hesitant to buy a home under a hoa, but we have got to find something bigger.   Experiences?  Advice?  Thanks",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3pdcpd",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "weaselsocrazy",
"media": null,
"score": 2,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 9,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3pdcpd/anyone_live_in_foxbank_in_moncks_corner/",
"name": "t3_3pdcpd",
"created": 1445301086,
"url": "https://www.reddit.com/r/Charleston/comments/3pdcpd/anyone_live_in_foxbank_in_moncks_corner/",
"author_flair_text": null,
"quarantine": false,
"title": "Anyone live in foxbank in Moncks corner?",
"created_utc": 1445272286,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 2
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I am looking to get tickets for Star Wars: The Force Awakens (HYPE!) where would be the best theater in the area. I am looking for the biggest screen and the theater that keep fresh bulbs in the projectors, comfortable seats, and loud/clear dolby digital or DTS audio. \nThanks all!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I am looking to get tickets for Star Wars: The Force Awakens (HYPE!) where would be the best theater in the area. I am looking for the biggest screen and the theater that keep fresh bulbs in the projectors, comfortable seats, and loud/clear dolby digital or DTS audio. \nThanks all!",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3pbgh1",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "oxygencube",
"media": null,
"score": 11,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 11,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3pbgh1/whats_the_best_movie_theater_in_the_area/",
"name": "t3_3pbgh1",
"created": 1445260326,
"url": "https://www.reddit.com/r/Charleston/comments/3pbgh1/whats_the_best_movie_theater_in_the_area/",
"author_flair_text": null,
"quarantine": false,
"title": "What's the best movie theater in the area?",
"created_utc": 1445231526,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 11
}
},
{
"kind": "t3",
"data": {
"domain": "imgur.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3paxz0",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "bigboatfear",
"media": null,
"score": 18,
"approved_by": null,
"over_18": false,
"hidden": false,
"preview": {
"images": [
{
"source": {
"url": "https://i.redditmedia.com/cO78jgbK4a0CO9CCsNGEpd43Dz5DM2cb8OX1-yRzeiY.jpg?s=eacced97065252ed0f088c6fb85f2f83",
"width": 3264,
"height": 2448
},
"resolutions": [
{
"url": "https://i.redditmedia.com/cO78jgbK4a0CO9CCsNGEpd43Dz5DM2cb8OX1-yRzeiY.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=4189a04f09c33316e648c18002fc3f54",
"width": 108,
"height": 81
},
{
"url": "https://i.redditmedia.com/cO78jgbK4a0CO9CCsNGEpd43Dz5DM2cb8OX1-yRzeiY.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=4b607205c05ba192989369e81fc7d8c3",
"width": 216,
"height": 162
},
{
"url": "https://i.redditmedia.com/cO78jgbK4a0CO9CCsNGEpd43Dz5DM2cb8OX1-yRzeiY.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=506745c07ecff723ec22ae269ccb3875",
"width": 320,
"height": 240
},
{
"url": "https://i.redditmedia.com/cO78jgbK4a0CO9CCsNGEpd43Dz5DM2cb8OX1-yRzeiY.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=145a1811ad80ac836a5e93febc387ed2",
"width": 640,
"height": 480
},
{
"url": "https://i.redditmedia.com/cO78jgbK4a0CO9CCsNGEpd43Dz5DM2cb8OX1-yRzeiY.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=960&amp;s=e20a2a0fc248aeda802ef1f7394c392d",
"width": 960,
"height": 720
},
{
"url": "https://i.redditmedia.com/cO78jgbK4a0CO9CCsNGEpd43Dz5DM2cb8OX1-yRzeiY.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=1080&amp;s=6026a9039a1e26eea2d5c5a3b83e2052",
"width": 1080,
"height": 810
}
],
"variants": {},
"id": "QnpCKFb_rKZYKYeCQOz52BLBNk6RvxFso1wwfhC40do"
}
]
},
"num_comments": 0,
"thumbnail": "http://a.thumbs.redditmedia.com/5oR3oRZTm2pKg5wJs9Ox_DAofgbhtTxOD_tE8JvZMR4.jpg",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"post_hint": "link",
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/3paxz0/my_first_experience_at_bowens_island_this_past/",
"name": "t3_3paxz0",
"created": 1445250310,
"url": "http://imgur.com/Ug2l1KD",
"author_flair_text": null,
"quarantine": false,
"title": "My first experience at Bowens Island this past Thursday.",
"created_utc": 1445221510,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 18
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hey guys. I&amp;#39;m in the process of planning a surprise birthday for my girlfriend. She will be out of town for her actual birthday so we will be celebrating the weekend before! I will be surprising her the day of Oct. 24. I want to take her to a nice restaurant downtown. She absolutely loves chicken Alfredo. So which restaurant offers the best chicken Alfredo downtown? Also I am looking for ideas for things to do after dinner. I was thinking about possibly bowling at the alley but I don&amp;#39;t know how much fun she would have with that. Any feedback is greatly appreciated! Thanks!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Hey guys. I'm in the process of planning a surprise birthday for my girlfriend. She will be out of town for her actual birthday so we will be celebrating the weekend before! I will be surprising her the day of Oct. 24. I want to take her to a nice restaurant downtown. She absolutely loves chicken Alfredo. So which restaurant offers the best chicken Alfredo downtown? Also I am looking for ideas for things to do after dinner. I was thinking about possibly bowling at the alley but I don't know how much fun she would have with that. Any feedback is greatly appreciated! Thanks!",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3pbdfz",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "Zberg24",
"media": null,
"score": 3,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 5,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3pbdfz/trying_to_plan_a_surprise_bday_for_the_gf_thanks/",
"name": "t3_3pbdfz",
"created": 1445258458,
"url": "https://www.reddit.com/r/Charleston/comments/3pbdfz/trying_to_plan_a_surprise_bday_for_the_gf_thanks/",
"author_flair_text": null,
"quarantine": false,
"title": "Trying to plan a surprise B-day for the GF. Thanks!",
"created_utc": 1445229658,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 3
}
},
{
"kind": "t3",
"data": {
"domain": "imgur.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3p8yns",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "JPEEZY95",
"media": null,
"score": 20,
"approved_by": null,
"over_18": false,
"hidden": false,
"preview": {
"images": [
{
"source": {
"url": "https://i.redditmedia.com/vo9vVNoPSiXwMtDpFu1DE8CJshdHuShni9FZ6HO_yZM.jpg?s=378e8189ae7d9276633521b136a540bf",
"width": 3264,
"height": 1836
},
"resolutions": [
{
"url": "https://i.redditmedia.com/vo9vVNoPSiXwMtDpFu1DE8CJshdHuShni9FZ6HO_yZM.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=6d69767792a23eca699ea6a9da10d39d",
"width": 108,
"height": 60
},
{
"url": "https://i.redditmedia.com/vo9vVNoPSiXwMtDpFu1DE8CJshdHuShni9FZ6HO_yZM.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=bbc09241c154840fe068bab8799d6990",
"width": 216,
"height": 121
},
{
"url": "https://i.redditmedia.com/vo9vVNoPSiXwMtDpFu1DE8CJshdHuShni9FZ6HO_yZM.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=17dd2b6347d20e102fba4243f9b1c53f",
"width": 320,
"height": 180
},
{
"url": "https://i.redditmedia.com/vo9vVNoPSiXwMtDpFu1DE8CJshdHuShni9FZ6HO_yZM.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=a182f13e08f97186926fbb43c53b5d8c",
"width": 640,
"height": 360
},
{
"url": "https://i.redditmedia.com/vo9vVNoPSiXwMtDpFu1DE8CJshdHuShni9FZ6HO_yZM.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=960&amp;s=0aac2976c10deda1730efb12f7745484",
"width": 960,
"height": 540
},
{
"url": "https://i.redditmedia.com/vo9vVNoPSiXwMtDpFu1DE8CJshdHuShni9FZ6HO_yZM.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=1080&amp;s=72a1daf5a7e6f37e6b2f933949fff5bf",
"width": 1080,
"height": 607
}
],
"variants": {},
"id": "ZNGTZCFcB8is_RowiObSX9Au6fY_fi4LULHJ21bld0o"
}
]
},
"num_comments": 1,
"thumbnail": "http://b.thumbs.redditmedia.com/2fPdwnMzbkXJ9SPW5eWVDsUV-Sv9dmhPRGX98MzdhUs.jpg",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"post_hint": "link",
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/3p8yns/picture_i_took_of_downtown_from_the_harbor/",
"name": "t3_3p8yns",
"created": 1445218535,
"url": "http://imgur.com/74POcJq",
"author_flair_text": null,
"quarantine": false,
"title": "Picture I took of downtown from the Harbor.",
"created_utc": 1445189735,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 20
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Anyone familiar with the SC teacher loan programs? Specifically, are they available for current teachers who would like to take out a loan for graduate school? &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Anyone familiar with the SC teacher loan programs? Specifically, are they available for current teachers who would like to take out a loan for graduate school? ",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3pak66",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "quigleygreg",
"media": null,
"score": 2,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 0,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3pak66/sc_teachers_loan_programs/",
"name": "t3_3pak66",
"created": 1445218467,
"url": "https://www.reddit.com/r/Charleston/comments/3pak66/sc_teachers_loan_programs/",
"author_flair_text": null,
"quarantine": false,
"title": "SC Teachers Loan Programs",
"created_utc": 1445214867,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 2
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I want to get some significant work done but I haven&amp;#39;t used any artists from this area before.  Can anyone make any recommendations and possibly link to the the artists work?  Thanks!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I want to get some significant work done but I haven't used any artists from this area before.  Can anyone make any recommendations and possibly link to the the artists work?  Thanks!",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3p8orx",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "getChester",
"media": null,
"score": 3,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 6,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3p8orx/lets_talk_about_tattoos/",
"name": "t3_3p8orx",
"created": 1445214234,
"url": "https://www.reddit.com/r/Charleston/comments/3p8orx/lets_talk_about_tattoos/",
"author_flair_text": null,
"quarantine": false,
"title": "Let's talk about tattoos",
"created_utc": 1445185434,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 3
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Just moved into Mt pleasant yesterday. Now ready to get out and watch some panthers football this afternoon but want to find the best place around here with good craft beer specials and a fun crowd. Throw out some ideas and recommendations? Thanks in advance. &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Just moved into Mt pleasant yesterday. Now ready to get out and watch some panthers football this afternoon but want to find the best place around here with good craft beer specials and a fun crowd. Throw out some ideas and recommendations? Thanks in advance. ",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3p88sj",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "AwesomeGuyB",
"media": null,
"score": 4,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 5,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3p88sj/best_place_to_watch_sunday_football_in_mtp/",
"name": "t3_3p88sj",
"created": 1445181376,
"url": "https://www.reddit.com/r/Charleston/comments/3p88sj/best_place_to_watch_sunday_football_in_mtp/",
"author_flair_text": null,
"quarantine": false,
"title": "Best place to watch Sunday football in MtP?",
"created_utc": 1445177776,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 4
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hey, I just moved to the area from NY where I was spoiled with the Mecca of all grocery stores, Wegmans. I am trying to find a grocery stores that has a scoop-your-own section or somewhere to purchase bulk nuts for a good price. If anyone has any places in mind I would love to find out!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Hey, I just moved to the area from NY where I was spoiled with the Mecca of all grocery stores, Wegmans. I am trying to find a grocery stores that has a scoop-your-own section or somewhere to purchase bulk nuts for a good price. If anyone has any places in mind I would love to find out!",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3p8gu6",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "rolleiflex6X6",
"media": null,
"score": 2,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 12,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3p8gu6/bulk_nuts_for_descent_price/",
"name": "t3_3p8gu6",
"created": 1445185364,
"url": "https://www.reddit.com/r/Charleston/comments/3p8gu6/bulk_nuts_for_descent_price/",
"author_flair_text": null,
"quarantine": false,
"title": "Bulk nuts for descent price",
"created_utc": 1445181764,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 2
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I know there&amp;#39;s a huge craft beer culture here in Charleston. If anyone uses the Untappd app I think it would be great to socially connect to some people who drink loads of different beers and keep up with everything. Anyone want to share their username? &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I know there's a huge craft beer culture here in Charleston. If anyone uses the Untappd app I think it would be great to socially connect to some people who drink loads of different beers and keep up with everything. Anyone want to share their username? ",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3p525n",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "ViciousPenguin",
"media": null,
"score": 20,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 13,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3p525n/anyone_else_use_untappd_app/",
"name": "t3_3p525n",
"created": 1445136214,
"url": "https://www.reddit.com/r/Charleston/comments/3p525n/anyone_else_use_untappd_app/",
"author_flair_text": null,
"quarantine": false,
"title": "Anyone else use Untappd app?",
"created_utc": 1445107414,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 20
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;What do you guys think of the candidates? Are you for Deerin, Tecklenburg, Stavrinakis, Gregorie, Washington, or Smith?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "What do you guys think of the candidates? Are you for Deerin, Tecklenburg, Stavrinakis, Gregorie, Washington, or Smith?",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3p43jh",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "itslazza",
"media": null,
"score": 17,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 5,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3p43jh/charleston_mayoral_election_discussion/",
"name": "t3_3p43jh",
"created": 1445120243,
"url": "https://www.reddit.com/r/Charleston/comments/3p43jh/charleston_mayoral_election_discussion/",
"author_flair_text": null,
"quarantine": false,
"title": "Charleston Mayoral Election Discussion",
"created_utc": 1445091443,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 17
}
},
{
"kind": "t3",
"data": {
"domain": "youtube.com",
"banned_by": null,
"media_embed": {
"content": "&lt;iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FMqqXTjg8438%3Ffeature%3Doembed&amp;url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DMqqXTjg8438%26feature%3Dyoutu.be&amp;image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FMqqXTjg8438%2Fhqdefault.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=youtube\" width=\"600\" height=\"338\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"width": 600,
"scrolling": false,
"height": 338
},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": {
"oembed": {
"provider_url": "https://www.youtube.com/",
"description": "Charleston, SC Police Officer decides to park his cop car in the parking lot of a local business. The officer was then seen takin goff his patrol belt putting it int he trunk then getting into another car with an unidentified woman and driving off.",
"title": "Police Car getting Towed or Pay Fine | Cop Parks illegally - Charleston, SC",
"url": "http://www.youtube.com/watch?v=MqqXTjg8438",
"type": "video",
"author_name": "Chad Walton",
"height": 338,
"width": 600,
"html": "&lt;iframe class=\"embedly-embed\" src=\"https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FMqqXTjg8438%3Ffeature%3Doembed&amp;url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DMqqXTjg8438%26feature%3Dyoutu.be&amp;image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FMqqXTjg8438%2Fhqdefault.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=youtube\" width=\"600\" height=\"338\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"thumbnail_width": 480,
"version": "1.0",
"provider_name": "YouTube",
"thumbnail_url": "https://i.embed.ly/1/image?url=https%3A%2F%2Fi.ytimg.com%2Fvi%2FMqqXTjg8438%2Fhqdefault.jpg&amp;key=b1e305db91cf4aa5a86b732cc9fffceb",
"thumbnail_height": 360,
"author_url": "https://www.youtube.com/user/chadwalton54"
},
"type": "youtube.com"
},
"link_flair_text": null,
"id": "3ozqvo",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "theninetyninthstraw",
"media": {
"oembed": {
"provider_url": "https://www.youtube.com/",
"description": "Charleston, SC Police Officer decides to park his cop car in the parking lot of a local business. The officer was then seen takin goff his patrol belt putting it int he trunk then getting into another car with an unidentified woman and driving off.",
"title": "Police Car getting Towed or Pay Fine | Cop Parks illegally - Charleston, SC",
"url": "http://www.youtube.com/watch?v=MqqXTjg8438",
"type": "video",
"author_name": "Chad Walton",
"height": 338,
"width": 600,
"html": "&lt;iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FMqqXTjg8438%3Ffeature%3Doembed&amp;url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DMqqXTjg8438%26feature%3Dyoutu.be&amp;image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FMqqXTjg8438%2Fhqdefault.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=youtube\" width=\"600\" height=\"338\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"thumbnail_width": 480,
"version": "1.0",
"provider_name": "YouTube",
"thumbnail_url": "https://i.ytimg.com/vi/MqqXTjg8438/hqdefault.jpg",
"thumbnail_height": 360,
"author_url": "https://www.youtube.com/user/chadwalton54"
},
"type": "youtube.com"
},
"score": 27,
"approved_by": null,
"over_18": false,
"hidden": false,
"preview": {
"images": [
{
"source": {
"url": "https://i.redditmedia.com/7ib51tg1YDCO9Ngh-J1EJsbAtSSES8a0teBbUTnYy0w.jpg?s=80c6fb9f9dc7dea437db9e8e36a66ae9",
"width": 480,
"height": 360
},
"resolutions": [
{
"url": "https://i.redditmedia.com/7ib51tg1YDCO9Ngh-J1EJsbAtSSES8a0teBbUTnYy0w.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=51b95c5ab2cbc4bde0deeebeebf597cf",
"width": 108,
"height": 81
},
{
"url": "https://i.redditmedia.com/7ib51tg1YDCO9Ngh-J1EJsbAtSSES8a0teBbUTnYy0w.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=6f7c4aaa1915a6ec47560b06846e135c",
"width": 216,
"height": 162
},
{
"url": "https://i.redditmedia.com/7ib51tg1YDCO9Ngh-J1EJsbAtSSES8a0teBbUTnYy0w.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=a62d34826eb92bc25a444d4da3d7a213",
"width": 320,
"height": 240
}
],
"variants": {},
"id": "Y3nKdi9dA7VvtaUhjd8kL64OTLiro_cysVDjJttOBgI"
}
]
},
"num_comments": 18,
"thumbnail": "http://b.thumbs.redditmedia.com/_IHlqCeYMzIacpX_1jqwndneeeYmjAp2dyIZRHx66zM.jpg",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {
"content": "&lt;iframe class=\"embedly-embed\" src=\"https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FMqqXTjg8438%3Ffeature%3Doembed&amp;url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DMqqXTjg8438%26feature%3Dyoutu.be&amp;image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FMqqXTjg8438%2Fhqdefault.jpg&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=youtube\" width=\"600\" height=\"338\" scrolling=\"no\" frameborder=\"0\" allowfullscreen&gt;&lt;/iframe&gt;",
"width": 600,
"scrolling": false,
"height": 338
},
"saved": false,
"removal_reason": null,
"post_hint": "rich:video",
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/3ozqvo/police_car_getting_towed_or_pay_fine_cop_parks/",
"name": "t3_3ozqvo",
"created": 1445008755,
"url": "https://www.youtube.com/watch?v=MqqXTjg8438&amp;feature=youtu.be",
"author_flair_text": null,
"quarantine": false,
"title": "Police Car getting Towed or Pay Fine | Cop Parks illegally - Charleston, SC",
"created_utc": 1445005155,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 27
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;About a year ago, I visited Charleston on a whim with some friends, and while looking for a decent place to park downtown, we happened across a small hole-in-the-wall sort of deli. It was owned/operated by an older couple, offered a great selection of sandwhiches, milkshakes, ice cream, and some other brunch-esque selections. Everything, including the ice cream, was made in-house, and everything we had was pretty damned wonderful.&lt;/p&gt;\n\n&lt;p&gt;I can&amp;#39;t recall the exact location, but I do know we didn&amp;#39;t drive anywhere once we got downtown (there were cheap parking meters right in front of this deli), and it was only a mile or two&amp;#39;s walk from the Black Tap where we went for coffee. &lt;/p&gt;\n\n&lt;p&gt;I realize this probably isn&amp;#39;t a whole lot to go on, but if I could come up with any finer details I&amp;#39;d have probably found it on Google already. ;D &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "About a year ago, I visited Charleston on a whim with some friends, and while looking for a decent place to park downtown, we happened across a small hole-in-the-wall sort of deli. It was owned/operated by an older couple, offered a great selection of sandwhiches, milkshakes, ice cream, and some other brunch-esque selections. Everything, including the ice cream, was made in-house, and everything we had was pretty damned wonderful.\n\nI can't recall the exact location, but I do know we didn't drive anywhere once we got downtown (there were cheap parking meters right in front of this deli), and it was only a mile or two's walk from the Black Tap where we went for coffee. \n\nI realize this probably isn't a whole lot to go on, but if I could come up with any finer details I'd have probably found it on Google already. ;D ",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3oz5sx",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "Totentag",
"media": null,
"score": 10,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 20,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3oz5sx/help_me_remember_a_small_restaurant_i_where_i_had/",
"name": "t3_3oz5sx",
"created": 1444997486,
"url": "https://www.reddit.com/r/Charleston/comments/3oz5sx/help_me_remember_a_small_restaurant_i_where_i_had/",
"author_flair_text": null,
"quarantine": false,
"title": "Help me remember a small restaurant I where I had brunch?",
"created_utc": 1444993886,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 10
}
},
{
"kind": "t3",
"data": {
"domain": "i.imgur.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3oxg1h",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "whycantibeyou",
"media": null,
"score": 49,
"approved_by": null,
"over_18": false,
"hidden": false,
"preview": {
"images": [
{
"source": {
"url": "https://i.redditmedia.com/OoH8ZH-dE-YbIxu9jYJdg4Jjy_Sqmtx8GafTWEPdAT0.jpg?s=e8fa9ddb7a4f87aeb807e834ca9144de",
"width": 3264,
"height": 2448
},
"resolutions": [
{
"url": "https://i.redditmedia.com/OoH8ZH-dE-YbIxu9jYJdg4Jjy_Sqmtx8GafTWEPdAT0.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=898492fe87e4807c0fc95c4c46495639",
"width": 108,
"height": 81
},
{
"url": "https://i.redditmedia.com/OoH8ZH-dE-YbIxu9jYJdg4Jjy_Sqmtx8GafTWEPdAT0.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=6165b22104d87866e7cfd735500769a4",
"width": 216,
"height": 162
},
{
"url": "https://i.redditmedia.com/OoH8ZH-dE-YbIxu9jYJdg4Jjy_Sqmtx8GafTWEPdAT0.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=4139e2e21468210dfb79b3d3e848b888",
"width": 320,
"height": 240
},
{
"url": "https://i.redditmedia.com/OoH8ZH-dE-YbIxu9jYJdg4Jjy_Sqmtx8GafTWEPdAT0.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=ed43eec5ab0de7623d40e5a9ee50c610",
"width": 640,
"height": 480
},
{
"url": "https://i.redditmedia.com/OoH8ZH-dE-YbIxu9jYJdg4Jjy_Sqmtx8GafTWEPdAT0.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=960&amp;s=433c137a2aa19f836d1e5f8adbf140e3",
"width": 960,
"height": 720
},
{
"url": "https://i.redditmedia.com/OoH8ZH-dE-YbIxu9jYJdg4Jjy_Sqmtx8GafTWEPdAT0.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=1080&amp;s=c1567bdf4d71d2177358d5dbf3f91206",
"width": 1080,
"height": 810
}
],
"variants": {},
"id": "Fy2hwaMvSbTHSQLR6eBcOZcQfceyocwgJwWT1h8tunw"
}
]
},
"num_comments": 0,
"thumbnail": "http://a.thumbs.redditmedia.com/EuJinG2IusEmnVWft1X4i9rVOoIOhK7sXdD3YmRc-58.jpg",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"post_hint": "image",
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/3oxg1h/found_this_guy_wandering_around_west_ashley_today/",
"name": "t3_3oxg1h",
"created": 1444959291,
"url": "http://i.imgur.com/id2gP6v.jpg",
"author_flair_text": null,
"quarantine": false,
"title": "Found this guy wandering around West Ashley today. Hope he finds his way home.",
"created_utc": 1444955691,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 49
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Welcome to our new &lt;strong&gt;weekly post&lt;/strong&gt; where we discuss any events or activities taking place this weekend in the Charleston area. You can find events by checking &lt;a href=\"http://www.charlestoncitypaper.com/charleston/EventSearch?narrowByDate=This%20Weekend\"&gt;Charleston City Paper&lt;/a&gt;, &lt;a href=\"http://chsbeer.org/events\"&gt;CHSBeer&lt;/a&gt;,  &lt;a href=\"http://metronomecharleston.com/calendar/\"&gt;Metronome&lt;/a&gt;, &lt;a href=\"http://www.holycitysinner.com/events/\"&gt;HolyCitySinner&lt;/a&gt;, &lt;a href=\"http://www.postandcourier.com/section/search&amp;amp;facet.filter=Keywords:Things%20to%20Do\"&gt;Post &amp;amp; Courier&lt;/a&gt;, or &lt;a href=\"http://www.charlestoncvb.com/visitors/events_news/charleston-events/\"&gt;Charleston CVB&lt;/a&gt;. Please post a link to an event page for additional information (if possible).&lt;/p&gt;\n\n&lt;p&gt;The goal is simple: to generate some discussion, learn about what&amp;#39;s happening in the area, arrange impromptu meetups, and maybe help out anyone visiting for the weekend.&lt;/p&gt;\n\n&lt;p&gt;Thanks for participating! Any questions, &lt;a href=\"https://www.reddit.com/message/compose?to=%2Fr%2Fcharleston\"&gt;please ask the mods&lt;/a&gt;.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Welcome to our new **weekly post** where we discuss any events or activities taking place this weekend in the Charleston area. You can find events by checking [Charleston City Paper](http://www.charlestoncitypaper.com/charleston/EventSearch?narrowByDate=This%20Weekend), [CHSBeer](http://chsbeer.org/events),  [Metronome](http://metronomecharleston.com/calendar/), [HolyCitySinner](http://www.holycitysinner.com/events/), [Post &amp; Courier](http://www.postandcourier.com/section/search&amp;facet.filter=Keywords:Things%20to%20Do), or [Charleston CVB](http://www.charlestoncvb.com/visitors/events_news/charleston-events/). Please post a link to an event page for additional information (if possible).\n\nThe goal is simple: to generate some discussion, learn about what's happening in the area, arrange impromptu meetups, and maybe help out anyone visiting for the weekend.\n\nThanks for participating! Any questions, [please ask the mods](https://www.reddit.com/message/compose?to=%2Fr%2Fcharleston).\n",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": "TGIF!",
"id": "3oz0g5",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "AutoModerator",
"media": null,
"score": 5,
"approved_by": null,
"over_18": false,
"hidden": false,
"preview": {
"images": [
{
"source": {
"url": "https://i.redditmedia.com/TjVs0b04DMddxkTXY6_DrxJJL2JSezOn2geOwhlqy7g.jpg?s=9610edfcef7d963e5a3c4431000a9128",
"width": 200,
"height": 200
},
"resolutions": [
{
"url": "https://i.redditmedia.com/TjVs0b04DMddxkTXY6_DrxJJL2JSezOn2geOwhlqy7g.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=625689bbbb152640753ae110bf415b4f",
"width": 108,
"height": 108
}
],
"variants": {},
"id": "Je4bqtZmh-W_FBqUqyUiOU51oUt2y3-RUGKLdSFid38"
}
]
},
"num_comments": 1,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": "tgif",
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"post_hint": "self",
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3oz0g5/weekend_roundup_october_16_2015/",
"name": "t3_3oz0g5",
"created": 1444993474,
"url": "https://www.reddit.com/r/Charleston/comments/3oz0g5/weekend_roundup_october_16_2015/",
"author_flair_text": "Robot Overlord",
"quarantine": false,
"title": "Weekend Roundup! October 16, 2015",
"created_utc": 1444989874,
"distinguished": "moderator",
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 5
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;So what do you think the most underrated restaurant in the tri-county is? &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "So what do you think the most underrated restaurant in the tri-county is? ",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3ox5lm",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "imagineskyscrapers",
"media": null,
"score": 17,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 28,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3ox5lm/your_thoughts_most_underrated_restaurant_in_the/",
"name": "t3_3ox5lm",
"created": 1444979712,
"url": "https://www.reddit.com/r/Charleston/comments/3ox5lm/your_thoughts_most_underrated_restaurant_in_the/",
"author_flair_text": null,
"quarantine": false,
"title": "Your Thoughts: Most Underrated Restaurant in the Charleston Area?",
"created_utc": 1444950912,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 17
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Is there somebody in your life who really deserves a night out and would love to see the SuicideGirls: Blackheart Burlesque show? Well, we want to give you the opportunity to go! Let us know in the comments who you&amp;#39;d take and why, and we&amp;#39;ll select one redditor who will receive a free pair of tickets to the show.&lt;/p&gt;\n\n&lt;p&gt;We&amp;#39;ll be performing at Music Farm on Monday, November 2nd @ 8PM. Show is 18+ only.&lt;/p&gt;\n\n&lt;p&gt;Winner to be announced 10/26. For a full list of show dates and ticket information, see: &lt;a href=\"http://blackheartburlesque.com\"&gt;http://blackheartburlesque.com&lt;/a&gt;&lt;/p&gt;\n\n&lt;p&gt;Good luck!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Is there somebody in your life who really deserves a night out and would love to see the SuicideGirls: Blackheart Burlesque show? Well, we want to give you the opportunity to go! Let us know in the comments who you'd take and why, and we'll select one redditor who will receive a free pair of tickets to the show.\n\nWe'll be performing at Music Farm on Monday, November 2nd @ 8PM. Show is 18+ only.\n\nWinner to be announced 10/26. For a full list of show dates and ticket information, see: http://blackheartburlesque.com\n\nGood luck!",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3oxcc1",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "RamboSuicide",
"media": null,
"score": 12,
"approved_by": null,
"over_18": false,
"hidden": false,
"preview": {
"images": [
{
"source": {
"url": "https://i.redditmedia.com/En-l_Pp2b28JgbHDwbYjekC3kpfZJb4XBmktgToWUPY.jpg?s=d15288cbaec68d6c1a3484c7462ecff8",
"width": 865,
"height": 586
},
"resolutions": [
{
"url": "https://i.redditmedia.com/En-l_Pp2b28JgbHDwbYjekC3kpfZJb4XBmktgToWUPY.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=2c06e847378016ef8ef437a4bef5b4d0",
"width": 108,
"height": 73
},
{
"url": "https://i.redditmedia.com/En-l_Pp2b28JgbHDwbYjekC3kpfZJb4XBmktgToWUPY.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=c2b11f230ff4614f228a70424c99749c",
"width": 216,
"height": 146
},
{
"url": "https://i.redditmedia.com/En-l_Pp2b28JgbHDwbYjekC3kpfZJb4XBmktgToWUPY.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=2ea1945097f21e9d6fc79256878b6a69",
"width": 320,
"height": 216
},
{
"url": "https://i.redditmedia.com/En-l_Pp2b28JgbHDwbYjekC3kpfZJb4XBmktgToWUPY.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=9c8bb5d9519885a2c2c4d279e27c27eb",
"width": 640,
"height": 433
}
],
"variants": {},
"id": "3Z9yhS3E0MiK58gFFt2NHyCQSJjgCBTtUTm-4eaQJMQ"
}
]
},
"num_comments": 11,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"post_hint": "self",
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3oxcc1/win_tickets_to_suicidegirls_blackheart_burlesque/",
"name": "t3_3oxcc1",
"created": 1444957561,
"url": "https://www.reddit.com/r/Charleston/comments/3oxcc1/win_tickets_to_suicidegirls_blackheart_burlesque/",
"author_flair_text": null,
"quarantine": false,
"title": "Win tickets to SuicideGirls: Blackheart Burlesque on 11/2!",
"created_utc": 1444953961,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 12
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;So what do you think the most overrated restaurant in the tri-county is? &lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "So what do you think the most overrated restaurant in the tri-county is? ",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3ox5uo",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "imagineskyscrapers",
"media": null,
"score": 9,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 32,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3ox5uo/your_thoughts_most_overrated_restaurant_in_the/",
"name": "t3_3ox5uo",
"created": 1444954615,
"url": "https://www.reddit.com/r/Charleston/comments/3ox5uo/your_thoughts_most_overrated_restaurant_in_the/",
"author_flair_text": null,
"quarantine": false,
"title": "Your Thoughts: Most Overrated Restaurant in the Charleston Area?",
"created_utc": 1444951015,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 9
}
},
{
"kind": "t3",
"data": {
"domain": "live5news.com",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": null,
"selftext": "",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3ow23h",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "darkcisnelle",
"media": null,
"score": 10,
"approved_by": null,
"over_18": false,
"hidden": false,
"preview": {
"images": [
{
"source": {
"url": "https://i.redditmedia.com/6ghe_AIN_Emvra68ZLTO8SxdmpfvVvNtgL-tL3MSx-k.jpg?s=dd7faf3bba6f0404fa4b9f56a1f75abb",
"width": 240,
"height": 320
},
"resolutions": [
{
"url": "https://i.redditmedia.com/6ghe_AIN_Emvra68ZLTO8SxdmpfvVvNtgL-tL3MSx-k.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=79aeafe1acfd088d2719327d56b213b1",
"width": 108,
"height": 144
},
{
"url": "https://i.redditmedia.com/6ghe_AIN_Emvra68ZLTO8SxdmpfvVvNtgL-tL3MSx-k.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=4b8f8093a32a4613a43d0711a37c387c",
"width": 216,
"height": 288
}
],
"variants": {},
"id": "d-3b08-ZmQ8N9MqFzCWQehmTSGb-FmPsR-2tN_UZc38"
}
]
},
"num_comments": 1,
"thumbnail": "http://a.thumbs.redditmedia.com/g7e8S-gTOKxTJBUF2ONqKlhGJ5xH2sh7zs-8rlhWbH4.jpg",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"post_hint": "link",
"stickied": false,
"from": null,
"is_self": false,
"from_id": null,
"permalink": "/r/Charleston/comments/3ow23h/flood_water_contaminates_oyster_beds_closure/",
"name": "t3_3ow23h",
"created": 1444938356,
"url": "http://www.live5news.com/story/30262749/flood-water-contaminates-oyster-beds-closure-impacting-local-businesses",
"author_flair_text": null,
"quarantine": false,
"title": "Flood water contaminates oyster beds; closure impacting local business | Charleston, SC",
"created_utc": 1444934756,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 10
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;Hi, I was born in Charleston, but only lived there about 3 months and haven&amp;#39;t been back since. I grew up in the midwest and have been to Columbia and Myrtle Beach, but never went to Charleston. I&amp;#39;m coming to visit on MLK weekend is there anything I should know about or see while in the city?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "Hi, I was born in Charleston, but only lived there about 3 months and haven't been back since. I grew up in the midwest and have been to Columbia and Myrtle Beach, but never went to Charleston. I'm coming to visit on MLK weekend is there anything I should know about or see while in the city?",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3ozf2i",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "Supreme_panda_god",
"media": null,
"score": 0,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 4,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3ozf2i/hi_going_to_visit_any_advice/",
"name": "t3_3ozf2i",
"created": 1445002895,
"url": "https://www.reddit.com/r/Charleston/comments/3ozf2i/hi_going_to_visit_any_advice/",
"author_flair_text": null,
"quarantine": false,
"title": "Hi, going to visit any advice?",
"created_utc": 1444999295,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 0
}
},
{
"kind": "t3",
"data": {
"domain": "self.Charleston",
"banned_by": null,
"media_embed": {},
"subreddit": "Charleston",
"selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I just moved to the area and was curious if there was anybody in charleston who listens to EDM music and knows about shows in the area (Also like Underground lowkey types of shows) if you could help me out id be very grateful. You can find me on social media as Sky_Guy_8 (Soundcloud , Mixcloud, Twitter. Vine)&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
"selftext": "I just moved to the area and was curious if there was anybody in charleston who listens to EDM music and knows about shows in the area (Also like Underground lowkey types of shows) if you could help me out id be very grateful. You can find me on social media as Sky_Guy_8 (Soundcloud , Mixcloud, Twitter. Vine)",
"likes": null,
"suggested_sort": null,
"user_reports": [],
"secure_media": null,
"link_flair_text": null,
"id": "3otq1k",
"from_kind": null,
"gilded": 0,
"archived": false,
"clicked": false,
"report_reasons": null,
"author": "Sky_guy_8",
"media": null,
"score": 12,
"approved_by": null,
"over_18": false,
"hidden": false,
"num_comments": 21,
"thumbnail": "self",
"subreddit_id": "t5_2qi6h",
"hide_score": false,
"edited": false,
"link_flair_css_class": null,
"author_flair_css_class": null,
"downs": 0,
"secure_media_embed": {},
"saved": false,
"removal_reason": null,
"stickied": false,
"from": null,
"is_self": true,
"from_id": null,
"permalink": "/r/Charleston/comments/3otq1k/charleston_edm_fans/",
"name": "t3_3otq1k",
"created": 1444893038,
"url": "https://www.reddit.com/r/Charleston/comments/3otq1k/charleston_edm_fans/",
"author_flair_text": null,
"quarantine": false,
"title": "Charleston EDM Fans?",
"created_utc": 1444889438,
"distinguished": null,
"mod_reports": [],
"visited": false,
"num_reports": null,
"ups": 12
}
}
],
"after": "t3_3otq1k",
"before": null
}
};
